# Generated by Django 3.0.3 on 2020-02-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maproom',
            name='x',
        ),
        migrations.RemoveField(
            model_name='maproom',
            name='y',
        ),
        migrations.AddField(
            model_name='maproom',
            name='coordinates',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
